### PR TITLE
Vespid Patch

### PR DESCRIPTION
**Pull request by UwUPlusUwU**
## About The Pull Request

Buffs the virgin Coxa stunmode and also adds a vendor

## Why It's Good For The Game

Because bzzt you dumb jannie

## Changelog
:cl: OnePlusOne
add: Vespid vendors are now a thing for mappers
/:cl:

### CODE REVIEW

**Comment by ghost** [comment]
+support

**Comment by UwUPlusUwU** [comment]
Also now fixes gun transformation please merge ASAP

**Comment by UwUPlusUwU** [comment]
Now fixes gun not working sweet allah

**Comment by MACIEKBAKI** [comment]
more GUNS? Is this what it is? GREAT, WE CAN FINALLY KILL THE XENOS

**Review by MarkSuckerberg — APPROVED** [review]

**Pull request merged**
