### PR TITLE
CLOWN STORE

### PR DESCRIPTION
**Pull request by MACIEKBAKI**
:cl: Honkus Maximus
add: Clown has access to a store full of clowning supplies.
/:cl:

[why]: # (Please add a short description [on the next line] of why you think these changes would benefit the game. If you can't justify it in words, it might not be worth adding:) 
honk

### CODE REVIEW

**Comment by MACIEKBAKI** [comment]
fyi testing I have done:

- it compiles
- you can buy items and they appear
- banana

**Comment by zeskorion** [comment]
> fyi testing I have done:
> 
> * it compiles
> * you can buy items and they appear
> * banana

travis sez otherwise

**Comment by MACIEKBAKI** [comment]
> 
> 
> > fyi testing I have done:
> > 
> > * it compiles
> > * you can buy items and they appear
> > * banana
> 
> travis sez otherwise

FUCK

**Comment by MACIEKBAKI** [comment]
I figured it out. It didn't compile becouse, whoopsie doo, I forgot to fucking make it compile the new file I added

**Comment by zeskorion** [comment]
> I figured it out. It didn't compile becouse, whoopsie doo, I forgot to fucking make it compile the new file I added

travis ruins everything, macie

**Comment by MACIEKBAKI** [comment]
compiles now, late comment becouse I was watching jojo. quickmerge pls

**Comment by MACIEKBAKI** [comment]
im not sure if the ability to insert bananas into the cartridge should be disabled by default or not

**Review by MarkSuckerberg — APPROVED** [review]

**Pull request merged**
